# Generated by Django 4.1 on 2023-01-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_alter_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
    ]
