# Generated by Django 4.1 on 2022-10-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_follow_accounts_follow_unique_relationships_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='accounts_follow_unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='accounts_follow_prevent_self_follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='to',
            new_name='fr',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='fromm',
            new_name='too',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('fr', 'too'), name='accounts_follow_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('fr', models.F('too')), _negated=True), name='accounts_follow_prevent_self_follow'),
        ),
    ]
