# Generated by Django 4.1 on 2022-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_follow_accounts_follow_unique_relationships_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', through='accounts.Follow', to='accounts.userprofile'),
        ),
    ]
