# Generated by Django 4.1 on 2022-10-30 11:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and ./_ only.', max_length=20, unique=True, validators=[accounts.models.CustomUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
